hours_window: 24
rss_feeds:
  - "https://www.google.com/alerts/feeds/EXEMPLE-1"
include_keywords: ["python"]
exclude_keywords: ["stage"]
tags: ["CDI","Paris"]
email_subject: "Veille d'offres d'emploi – résumé quotidien"
email:
  from: "Votre Nom <vous@example.com>"
  to: ["vous@example.com"]
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "votre-adresse@gmail.com"
    password: "VOTRE_MOT_DE_PASSE_APPLICATION"
    use_tls: true
